import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Card } from '../components/Card';
import { useAsync } from '../hooks/useAsync';
import { getMetrics } from '../lib/api';
export function MetricsOverviewPage() {
    var _a;
    var _b = useAsync(getMetrics, []), metrics = _b.data, loading = _b.loading;
    return (_jsxs("div", { className: "grid", style: { gap: 16 }, children: [_jsxs("div", { children: [_jsx("h1", { className: "page-title", children: "\u30E1\u30C8\u30EA\u30AF\u30B9\u4E00\u89A7" }), _jsx("p", { className: "page-subtitle", children: "scoreboard objective \u3068\u5358\u4F4D\u3001\u8AAC\u660E\u3092\u78BA\u8A8D\u3057\u3001\u30AB\u30FC\u30C9\u3092\u62BC\u3057\u3066\u65E5\u6B21\u5C65\u6B74\u3078\u79FB\u52D5\u3067\u304D\u307E\u3059\u3002" })] }), _jsx(Card, { title: "\u30E1\u30C8\u30EA\u30AF\u30B9", subtitle: loading ? '読み込み中...' : "".concat((_a = metrics === null || metrics === void 0 ? void 0 : metrics.length) !== null && _a !== void 0 ? _a : 0, " \u4EF6"), children: _jsxs("div", { className: "card-grid", children: [(metrics || []).map(function (metric) { return (_jsxs(Link, { to: "/metrics/".concat(metric.objectiveName, "/history"), className: "glass-card", style: { padding: 14, textDecoration: 'none' }, children: [_jsxs("div", { className: "card-header", style: { marginBottom: 6 }, children: [_jsxs("div", { children: [_jsx("div", { className: "label", style: { marginBottom: 2 }, children: metric.displayName }), _jsx("div", { className: "hint", children: metric.description })] }), _jsx("span", { className: "pill ".concat(metric.isEnabled ? 'status-online' : 'status-offline'), children: metric.isEnabled ? '有効' : '無効' })] }), _jsxs("div", { className: "grid", style: { gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 8 }, children: [_jsxs("div", { className: "surface-muted", children: [_jsx("div", { className: "muted", children: "objective" }), _jsx("div", { style: { fontWeight: 700 }, children: metric.objectiveName })] }), _jsxs("div", { className: "surface-muted", children: [_jsx("div", { className: "muted", children: "\u5358\u4F4D" }), _jsx("div", { style: { fontWeight: 700 }, children: metric.unit })] }), _jsxs("div", { className: "surface-muted", children: [_jsx("div", { className: "muted", children: "\u6700\u7D42\u66F4\u65B0" }), _jsx("div", { className: "hint", children: metric.updatedAt ? new Date(metric.updatedAt).toLocaleString('ja-JP') : '---' })] })] }), _jsx("div", { className: "muted", style: { marginTop: 8, fontSize: 12 }, children: "\u30AF\u30EA\u30C3\u30AF\u3067\u5C65\u6B74\uFF08\u30D0\u30FC\u30B0\u30E9\u30D5\uFF09\u3078" })] }, metric.id)); }), (metrics || []).length === 0 && _jsx("div", { className: "muted", children: "\u307E\u3060\u30E1\u30C8\u30EA\u30AF\u30B9\u304C\u3042\u308A\u307E\u305B\u3093" })] }) })] }));
}
